# -*- coding: utf-8 -*-
# Deployment settings for Stars.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.2/s3e/makefile_builder/mkb.py', 'c:/Users/Vinicius/Desktop/Yes or No/Stars/Stars.mkb', '--deploy-only', '--hub-data', 'C:/Users/Vinicius/Desktop/Yes or No/Stars/project_Stars/mkb-windows.txt', '--buildenv=VC12X']
mkb = 'c:/Users/Vinicius/Desktop/Yes or No/Stars/Stars.mkb'
mkf = ['c:\\marmalade\\7.2\\extensions\\s3ewebview\\s3ewebview.mkf', 'c:\\marmalade\\7.2\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.2\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.2\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.2\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.2\\extensions\\s3efacebook\\s3efacebook.mkf', 'c:\\marmalade\\7.2\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.2\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.2\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.2\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.2\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.2\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.2\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.2\\modules\\iw2dscenegraph\\iw2dscenegraph.mkf', 'c:\\marmalade\\7.2\\modules\\iw2dscenegraphcore\\iw2dscenegraphcore.mkf', 'c:\\marmalade\\7.2\\modules\\iwtween\\iwtween.mkf', 'c:\\users\\vinicius\\desktop\\yes or no\\stars\\modules\\soundengine\\soundengine.mkf', 'c:\\marmalade\\7.2\\extensions\\s3eflurry\\s3eflurry.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Vinicius/Desktop/Yes or No/Stars/data/audio', 'audio', 0),
    ('c:/Users/Vinicius/Desktop/Yes or No/Stars/data/textures', 'textures', 0),
    ('c:/Users/Vinicius/Desktop/Yes or No/Stars/data-ram/data-gles1,c:/Users/Vinicius/Desktop/Yes or No/Stars/data', '.', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/s3eWebView.js', 's3eWebView.js', 0),
    ('c:/marmalade/7.2/extensions/s3efacebook/source/iphone/facebook-ios-sdk/FacebookSDK.framework/Versions/A/Resources/FacebookSDKResources.bundle/FBDialog/images/fbicon.png', 'FacebookSDKResources.bundle/FBDialog/images/fbicon.png', 0),
    ('c:/marmalade/7.2/extensions/s3efacebook/source/iphone/facebook-ios-sdk/FacebookSDK.framework/Versions/A/Resources/FacebookSDKResources.bundle/FBDialog/images/close.png', 'FacebookSDKResources.bundle/FBDialog/images/close.png', 0),
    ('c:/marmalade/7.2/extensions/s3efacebook/source/iphone/facebook-ios-sdk/FacebookSDK.framework/Versions/A/Resources/FacebookSDKResources.bundle/FBDialog/images/close@2x.png', 'FacebookSDKResources.bundle/FBDialog/images/close@2x.png', 0),
    ('c:/marmalade/7.2/extensions/s3efacebook/facebook-winclient-sdk-master/Source/Facebook.Client-WindowsStore/FacebookDialogPage.xaml', 'FacebookDialogPage.xaml', 0),
]

assets['WebView32Assets'] = [
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/locales', 'locales', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/avcodec-53.dll', 'avcodec-53.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/avformat-53.dll', 'avformat-53.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/avutil-51.dll', 'avutil-51.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/chrome.pak', 'chrome.pak', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/d3dcompiler_43.dll', 'd3dcompiler_43.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/d3dx9_43.dll', 'd3dx9_43.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/icudt.dll', 'icudt.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/libcef.dll', 'libcef.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/libEGL.dll', 'libEGL.dll', 0),
    ('c:/marmalade/7.2/extensions/s3ewebview/lib/win32/libGLESv2.dll', 'libGLESv2.dll', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Stars'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Stars'
    long_caption = 'Stars'
    version = [0, 0, 1]
    config = ['c:/Users/Vinicius/Desktop/Yes or No/Stars/data/app.icf']
    data_dir = 'c:/Users/Vinicius/Desktop/Yes or No/Stars/data'
    iphone_link_lib = ['s3eWebView', 's3eFacebook', 'FlurryAnalytics', 's3eFlurry']
    osx_ext_dll = ['c:/marmalade/7.2/extensions/s3ewebview/lib/osx/libs3eWebView.dylib', 'c:/marmalade/7.2/extensions/s3eflurry/lib/osx/libs3eFlurry.dylib']
    ws8_ext_capabilities = []
    android_external_res = ['c:/marmalade/7.2/extensions/s3efacebook/facebook-android-sdk/facebook/res']
    win32_ext_dll = ['c:/marmalade/7.2/extensions/s3ewebview/lib/win32/s3eWebView.dll', 'c:/marmalade/7.2/extensions/s3eflurry/lib/win32/s3eFlurry.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['c:/marmalade/7.2/extensions/s3ewebview/lib/iphone', 'c:/marmalade/7.2/extensions/s3efacebook/lib/iphone', 'c:/marmalade/7.2/extensions/s3eflurry/lib/iphone']
    android_extra_application_manifest = ['c:/marmalade/7.2/extensions/s3efacebook/source/android/extra_app_manifest.xml']
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    iphone_appid = 'com.yesornogames.countingstarts'
    android_external_jars = ['c:/marmalade/7.2/extensions/s3ewebview/lib/android/s3eWebView.jar', 'c:/marmalade/7.2/extensions/s3efacebook/lib/android/s3eFacebook.jar', 'c:/marmalade/7.2/extensions/s3efacebook/facebook-android-sdk/libs/android-support-v4.jar', 'c:/marmalade/7.2/extensions/s3efacebook/lib/android/annotations-4.1.1.4.jar', 'c:/marmalade/7.2/extensions/s3eflurry/lib/android/s3eFlurry.jar', 'c:/marmalade/7.2/extensions/s3eflurry/lib/android/FlurryAgent.jar']
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = ['c:/marmalade/7.2/extensions/s3ewebview/lib/wp8/s3eWebViewExtension.dll', 'c:/marmalade/7.2/extensions/s3efacebook/lib/wp8/s3eFacebookExtension.dll', 'c:/marmalade/7.2/extensions/s3eflurry/lib/wp8/s3eFlurryExtension.dll']
    iphone_bundle_url_name = 'com.yesornogames.countingstarts'
    ws81_ext_sdk_ref = []
    iphone_link_opts = ['-F$MARMALADE_ROOT/extensions/s3eFacebook/source/iphone/facebook-ios-sdk -framework FacebookSDK -weak_framework AdSupport -weak_framework Accounts -weak_framework Social -lsqlite3', '-framework SystemConfiguration -framework Security']
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = ['c:/marmalade/7.2/extensions/s3ewebview/lib/wp8/s3eWebViewManaged.dll', 'c:/marmalade/7.2/extensions/s3efacebook/lib/wp8/s3eFacebookManaged.dll', 'c:/marmalade/7.2/extensions/s3efacebook/facebook_wp8_lib/Facebook.Client.dll', 'c:/marmalade/7.2/extensions/s3efacebook/facebook_wp8_lib/Facebook.dll', 'c:/marmalade/7.2/extensions/s3eflurry/lib/wp8/FlurryWP8SDK.dll', 'c:/marmalade/7.2/extensions/s3eflurry/lib/wp8/s3eFlurryManaged.dll']
    android_so = ['c:/marmalade/7.2/extensions/s3ewebview/lib/android/libs3eWebView.so', 'c:/marmalade/7.2/extensions/s3efacebook/lib/android/libs3eFacebook.so', 'c:/marmalade/7.2/extensions/s3eflurry/lib/android/libs3eFlurry.so']
    iphone_bundle_url_schemes = 'fd<FACEBOOK_APP_ID>'
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_gcc_x86/Stars.so',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_gcc_x86/Stars.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_gcc_x86_tizen/Stars.s86',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_gcc_x86_tizen/Stars.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_gcc_mips/Stars.so',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_gcc_mips/Stars.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_gcc_arm/Stars.s3e',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_gcc_arm/Stars.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_gcc_mips/Stars.so',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_gcc_mips/Stars.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_gcc_x86_android/Stars.so',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_gcc_x86_android/Stars.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_arm/Stars.s3e',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_arm/Stars.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Debug_Stars_VC12X_x86/Stars.s86',
                   'release' : r'c:/Users/Vinicius/Desktop/Yes or No/Stars/build_stars_vc12x/Release_Stars_VC12X_x86/Stars.s86',
                 },
        }
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
